# Generated by Django 5.2.4 on 2025-07-31 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_is_verified_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'email'), ('google', 'google'), ('facebook', 'facebook')], default='email', max_length=8),
        ),
    ]
