# Generated by Django 5.2.4 on 2025-08-02 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='location',
        ),
        migrations.AddField(
            model_name='property',
            name='air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(default='Lagos', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='currency',
            field=models.CharField(choices=[('NGN', '₦'), ('USD', '$'), ('EUR', '€'), ('GBP', '£')], default='NGN', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='dishwasher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='fireplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='security_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(default='Lagos', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='street_address',
            field=models.CharField(default='Ajao', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('House', 'House'), ('Condo', 'Condo'), ('Studio', 'Studio'), ('Commercial', 'Commercial')], default='Apartment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='walk_in_closet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='washer_dryer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='zip_code',
            field=models.CharField(default='100001', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.IntegerField(blank=True, help_text='Area in square feet', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.CharField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4+', '4+')]),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.CharField(choices=[('Studio', 'Studio'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5+', '5+')]),
        ),
    ]
